### ISSUE TITLE
This QuickStart confuses me

### ISSUE THREAD

**Issue by yobyot** [aws-quickstart/quickstart-microsoft-activedirectory#1]
Hello,
I need to subset this quick start to do something very specific: launch two Windows Server 2012 R2 instances into an existing VPC, create a domain controller with all roles from one and join the second instance to the first DC with all roles. I'm also a bit of CloudFormation newbie. My plan was to find the code in this quick start that does that and modify it for my needs.

However, that's easier said than done. Can the authors recommend an approach to slimming this template down? I am especially confused about the role of the quick start assets loaded to/from S3. Where do they come from and are they what the wait conditions are set to await completion of?

Thx!

**Comment by santiagocardenas** [comment]
I would suggest to take a look at the following template which I believe does what you're looking for:
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/templates/ad-2012r2-1.template

It uses an existing VPC to create a new Active Directory domain forest by promoting one instance to domain controller, then promoting the second instance to the same domain of the first instance. It does a few additional things like configuring a CA as well which may or may not be needed by your use case.

**Comment by yobyot** [comment]
Thanks, Santiago, for the near-instant response. I'll give this a try.

**Comment by LawrenceHwang** [comment]
Hi yobyot,

I had similar challenges previously. (Using Win 2016)

Instead of just using CFN and CFN-Init. I ended up combining the CFN and PowerShell DSC (xActiveDirectory resource). It's a different mindset but works pretty well. The quick start guide might help you out:
https://s3.amazonaws.com/quickstart-reference/microsoft/powershelldsc/latest/doc/Windows_PowerShell_DSC_on_AWS.pdf

Cheers,
L

**Comment by santiagocardenas** [comment]
Closing this question. Let us know if you need any other help.

Thanks,
Santiago
