### ISSUE TITLE
Install-ADDSForest.ps1 doesn't use the parameter: DomainNetBIOSName

### ISSUE THREAD

**Issue by jameszh** [aws-quickstart/quickstart-microsoft-activedirectory#10]
The script: Install-ADDSForest.ps1 doesn't use the parameter: DomainNetBIOSName at all when call Install-ADDSForest, I have to specify different DomainNetBIOSName.

**Comment by Fishbowler** [comment]
Came across the same thing. The script isn't being passed the correct value either. Opened PR #20 to address.
