### ISSUE TITLE
t2.small instances

### ISSUE THREAD

**Issue by dandill-eng** [aws-quickstart/quickstart-microsoft-activedirectory#111]
I've notice the CF code here doesn't support t2.small instances in the main/sub modules. That instance type does fall within the specs for the OSes, and would be handy for smaller environments, labs, etc. Is this intentional? If not I can throw in a commit to update that, just wasn't sure if there was a list of supported instance types that t2.small wasn't on or something like that.

Example:

ADServerInstanceType:
    AllowedValues:
      - t2.medium
      - t3.medium
      - t2.large
      - t3.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
    Default: m5.large
    Description: Amazon EC2 instance type for Active Directory Controller instances
    Type: String

**Comment by girvenj** [comment]
t2.small is the base size for the Windows Server OS, if you add AD you are adding additional overhead.  I would recommend with AD to have at least 4 GB of RAM to start with.  Active Directory is a database and is RAM sensitive.

**Comment by dandill-eng** [comment]
I'm not sure I follow your individual recommendations if you're saying that should apply broadly to the public. t2.small exceeds the required specs for Windows Server 2019 per Microsoft, t2.micro would even be within requirements: https://docs.microsoft.com/en-us/windows-server/get-started-19/sys-reqs-19  If you have a Microsoft link for t2.medium being minimum spec for AD, I'd be interested to read up on it. I'm sure there are other individuals that would say m4.large is the recommendation right?

Overall likely the right answer is to develop a baseline and monitor and configure according to your org, I'm just more wondering why this template has a higher minimum that pushes people into higher AWS costs, that might not be justified by Microsoft requirements or resource needs.

And yes, people can always create/modify their own cloudformation code. Hopefully this doesn't come across as pedantic...

**Comment by girvenj** [comment]
The default for the QuickStart is the full GUI with desktop experience: 512 MB (2 GB for Server with Desktop Experience installation option)  So the minimum that Microsoft recommends is 2 GB if running 2019 with a GUI.  Add on the load of running AD, I would recommend it is safe to start with a t2/3 medium.  Here is a good reference on DC sizing: https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services#ram  Based on their sizing even a brand new domain DC should have: at least 3.4GB of RAM.  Now if you deployed using core you could drop about .75GB - 1GB of RAM.  You will still be over 2GB.
