### ISSUE TITLE
Documentation does not match what is deployed by QuickStart for Security Groups

### ISSUE THREAD

**Issue by andrewclarkAC** [aws-quickstart/quickstart-microsoft-activedirectory#112]
The documentation https://aws-quickstart.github.io/quickstart-microsoft-activedirectory/#_security indicates that three security groups are created:
**DomainControllerSG** with ports for TCP5985, TCP53, UDP53, TCP80, TCP3389 from VPC CIDR and all from self and  UDP123, TCP135, UDP138, UDP137, TCP139, TCP445, UDP445, TCP464, UDP464, TCP49152-65535, UDP49152-65535, TCP389, UDP389, TCP636, TCP3268, TCP3269, TCP88, UDP88, UDP67, UDP2535, TCP9389, TCP5722, UDP5355, (ICMP -1) from DomainMemberSG
**DomainMemberSG** with ports for UDP88, TCP88, TCP445, UDP445, TCP49152-65535, UDP49152-65535, TCP389, UDP389, TCP636 from the AD controllers
**RDGWSecurityGroup** with ports for TCP3389 from RDGWCIDR

However, the CloudFormation Stacks create only two security groups with names and rules that differ from the documentation:
**DomainControllersSecurityGroup** with ports for UDP445, UDP138, UDP49152   - 65535, UDP464, TCP464, TCP49152   - 65535, UDP389, UDP53, TCP389, UDP123, TCP3389, TCP445, TCP9389, TCP5985, TCP3268, TCP88, TCP135, TCP636, 
TCP3269, TCP53, UDP88 and all from self
**DomainMembersSecurityGroup** with ports for TCP3389, TCP5985, TCP5986

**Comment by davmayd** [comment]
Hi @andrewclarkAC. If you deploy this Quick Start into a new VPC by default it deploys a Remote Desktop Gateway instance in an auto-scaling group (https://github.com/aws-quickstart/quickstart-microsoft-rdgateway) which is where the RDGWSecurityGroup comes from. I'll get the documentation updated with the correct ports. Thanks for catching this!

**Comment by davmayd** [comment]
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/commit/887bdbf6c3564a633ae6f3644be0bdb5107c1573
