### ISSUE TITLE
Scenario 1: intermittent errors running SSM automation, possibly due to DNS

### ISSUE THREAD

**Issue by crh23** [aws-quickstart/quickstart-microsoft-activedirectory#113]
When deploying the Quick Start in scenario 1 the SSM automation sometimes freezes at the step `configDC1`.

On investigation, I found that during this frozen state the DC1 instance could not be reached by SSM Session Manager. Connecting via RDP and running `Get-DnsClientServerAddress` revealed that no DNS server was configured (and so the SSM agent could not reach ssm.amazonaws.com). I encountered this issue quite a few times, and manually running `Start-DscConfiguration` via RDP would allow the automation to resume.

I believe this is due to an issue in `scripts/ConfigDC1.ps1`. DnsServerAddress[DnsServerAddress] (line 211) depends on [WindowsFeature]DNS, but [NetIPInterface]DisableDhcp (line 193) does not, so if a reboot occurs between those two resources then no DNS server will be configured at boot. Manually running `Start-DscConfiguration` would then resume the configuration, correctly setting the DNS server to `127.0.0.1`.

I think I was able to resolve the problem by adding [WindowsFeature]DNS as a DependsOn for [NetIPInterface]DisableDhcp, [IPAddress]SetIP and [DefaultGatewayAddress]SetDefaultGateway, but this does produce a warning when [WindowsFeature]DNS is installing since a static IP is not set.
Lines 193-216 in my updated script are now
```
        NetIPInterface DisableDhcp {
            Dhcp           = 'Disabled'
            InterfaceAlias = 'Primary'
            AddressFamily  = 'IPv4'
            DependsOn      = '[NetAdapterName]RenameNetAdapterPrimary', '[WindowsFeature]DNS'
        }
        IPAddress SetIP {
            IPAddress      = $IPADDR
            InterfaceAlias = 'Primary'
            AddressFamily  = 'IPv4'
            DependsOn      = '[NetAdapterName]RenameNetAdapterPrimary', '[WindowsFeature]DNS', '[NetIPInterface]DisableDhcp'
        }
        DefaultGatewayAddress SetDefaultGateway {
            Address        = $GatewayAddress
            InterfaceAlias = 'Primary'
            AddressFamily  = 'IPv4'
            DependsOn      = '[NetAdapterName]RenameNetAdapterPrimary', '[WindowsFeature]DNS', '[NetIPInterface]DisableDhcp'
        }
        DnsServerAddress DnsServerAddress {
            Address        = '127.0.0.1'
            InterfaceAlias = 'Primary'
            AddressFamily  = 'IPv4'
            DependsOn      = '[WindowsFeature]DNS', '[NetIPInterface]DisableDhcp'
        }
```
I am not certain if this is the correct way to fix the issue, or even if I have correctly identified the root cause of the issue I was having, but it seemed to work for me.

**Comment by davmayd** [comment]
Fixed by https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/114
