### ISSUE TITLE
Extend quickstart to allow secure seamless domain joins of Non-Windows Instances

### ISSUE THREAD

**Issue by mmeidlinger** [aws-quickstart/quickstart-microsoft-activedirectory#115]
Non-Windows instances need credentials when joining an AD domain, but giving all instances access to the Admin credential that the quickstart stores in secrets manager does not meet security best practices. 

For a secure setup, the [AWS documentation suggests to create a AD user with minimal privileges to join a hosts to the domain](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/seamlessly_join_linux_instance.html#seamless-linux-prereqs). 

I suggest to add an additional optional parameter to the quickstart to optionally store these credentials in secrets manager and create the corresponding user  [while setting up the MGMT1 instance](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/152fda102e8514604eaf201be381d814438b2047/templates/mgmt-1.template.yaml#L530).

**Comment by girvenj** [comment]
The repo is open source feel free to make the change and submit a pull request.  I agree it should be an optional parameter with a default value of "No" do not create the Secret.

**Comment by mmeidlinger** [comment]
Hi! I have [implemented the change in a dedicated branch](https://github.com/mmeidlinger/quickstart-microsoft-activedirectory/commit/bad2149ebcfd90a05d0c0b40b957f55c194912f8), but I am currently struggling to debug an issue. I guess this will be fairly easy to spot for someone with some powershell experience but I struggle to resolve it as this is my first touch point with PS. 

I have [extended PS Module to contain a function to create the credentials](https://github.com/mmeidlinger/quickstart-microsoft-activedirectory/blob/bad2149ebcfd90a05d0c0b40b957f55c194912f8/scripts/Modules/Module-AD/Module-AD.psm1#L1235) which I call [from the SSM automation that sets up the management instance]( https://github.com/mmeidlinger/quickstart-microsoft-activedirectory/blob/bad2149ebcfd90a05d0c0b40b957f55c194912f8/templates/mgmt-1.template.yaml#L552). In the CloudWatch logs of the SSM automation, I see that the secret can be loaded, but it fails to create an AD User and set the permissions. Oddly enough, the exact same function works just fine if I log in to the management instance after the fact and run a script like so:
```powershell
#script.ps1
Import-Module -Name 'C:\AWSQuickstart\Module-AD\Module-AD.psm1' -Force
Set-NonWindowsDomainJoin-Credentials -SecretArn arn:xxxx:....
```
( I [prevented the deletion of the module files](https://github.com/mmeidlinger/quickstart-microsoft-activedirectory/blob/bad2149ebcfd90a05d0c0b40b957f55c194912f8/scripts/Modules/Module-AD/Module-AD.psm1#L941) for debugging)

My guess is  this is related to the execution context but I can't see what the issue is. Also, I would love to get more debugging output [when creating the New AD user](https://github.com/mmeidlinger/quickstart-microsoft-activedirectory/blob/bad2149ebcfd90a05d0c0b40b957f55c194912f8/scripts/Modules/Module-AD/Module-AD.psm1#L1258) which is the first command to fail but also don't know how to make that happen.
