### ISSUE TITLE
ad-2012r2-1.template fails to launch in multiple regions. AMIs not cleared for launch. 

### ISSUE THREAD

**Issue by carrollh** [aws-quickstart/quickstart-microsoft-activedirectory#12]
Create fails for DomainController1 with event message "API: ec2:RunInstances Not authorized for images: [ami-a04e16cf]" in Mumbai (ap-south-1).

I also get the same error in Seoul (ap-northeast-2), but with ami-9e75d9f0. 

I stopped trying after that.

**Comment by carrollh** [comment]
It doesn't seem to work anywhere. Maybe the AMIs haven't made it to public status in the aws marketplace yet?

**Comment by kamarja** [comment]
Hi Heath,
We are have updated the AMI's and testing now. Keep you posted.

**Comment by kamarja** [comment]
Heath, this issue has been resolved.
