### ISSUE TITLE
ad3 template does not include RDP 

### ISSUE THREAD

**Issue by cszelesbbs** [aws-quickstart/quickstart-microsoft-activedirectory#129]
the bring your own vpc ad3 template does not include RDP gtwy to access resources externally where the other from scratch vpc builds do. Not sure if this is oversight or intended. Would like to see existing vpc include this.

**Comment by girvenj** [comment]
I just checked the ad-main-3.template.yaml and it  includes the RDGW option.

**Comment by davmayd** [comment]
"Existing VPC" options don't typically include the RD Gateway submodule, since customers are expected to manage the remote access options for their own VPCs.
