### ISSUE TITLE
ad-2012r2-1.template not updated for Paris region yet.

### ISSUE THREAD

**Issue by carrollh** [aws-quickstart/quickstart-microsoft-activedirectory#13]
I get the following Create Failed event message when trying to launch it in Paris (eu-west-3):
Template error: Unable to get mapping for AWSAMIRegionMap::eu-west-3::WS2012R2

The Mappings section of the template just needs to have the Paris region added with the correct ami id.

**Comment by santiagocardenas** [comment]
Older templates are being deprecated in favor of the ad-1.template, ad-2.template, and ad-3.template ones. These use Windows Server 2016.

We'll be eliminating old templates soon after Quick Starts start consuming the new ones.
