### ISSUE TITLE
GovCloud AD Deployment Issues

### ISSUE THREAD

**Issue by applebaggins** [aws-quickstart/quickstart-microsoft-activedirectory#16]
The ad-n.template files have the following issues when deploying in GovCloud:

1. The 'AWSAMIRegionMap' does not contain an entry for 'us-gov-west-1' with a corresponding AMI

The ad-1.template file has the following issue when deploying in GovCloud:

1. The partition listed in the Resource of the policy for AD-SSM-Parameters on line 521 is hard-coded to 'arn:aws:ssm' instead of having a Fn;Sub: ["arn:${Partition} tied to the GovCloudCondition.

**Comment by virtlima** [comment]
Thank you for bringing this to our attention, it has been updated in the quick start.
