### ISSUE TITLE
How to referance this template in S3

### ISSUE THREAD

**Issue by elvirk** [aws-quickstart/quickstart-microsoft-activedirectory#2]
Hi,

I'm new to Git and AWS and I was trying to use cloud formation to deploy "https://docs.aws.amazon.com/quickstart/latest/active-directory-ds/welcome.html" but when ever I run this template from Cloud Stack if errors and said that following doesn't exist:  "submodules/quickstart-aws-vpc",
                            "templates/aws-vpc.template"
I created those folders in my S3 and uploaded template but still doesn't work.

How do I ref. Github in AWS CloudFormation? I would appreciate if you could help.

**Comment by kamarja** [comment]
Hi,
Try the following:
1.) git clone git@github.com:aws-quickstart/quickstart-microsoft-activedirectory.git
2.) cd quickstart-microsoft-activedirectory
3.) git submodule update --init --recursive
4.) aws s3 cp --recursive /full-path-to/quickstart-microsoft-activedirectory s3://your-s3-bucket

After this try launching your template. Let me know if that helps.

**Comment by elvirk** [comment]
thank you kamarja - step 4 doesn't work I'm getting following error 
aws : The term 'aws' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or i
path was included, verify that the path is correct and try again.
At line:1 char:1
+ aws s3 cp --recursive /full-path-to/quickstart-microsoft-activedirect ... 

I'm providing full path to quickstart-microsoft-activedirect but it doesn't work

**Comment by kamarja** [comment]
You need to install the awscli tools. Follow this page: http://docs.aws.amazon.com/cli/latest/userguide/installing.html

**Comment by santiagocardenas** [comment]
Closing this question. Let us know if you need any other help.

Thanks,
Santiago
