### ISSUE TITLE
 DomainDNSName max length varies in different templates

### ISSUE THREAD

**Issue by SubinGeorge22** [aws-quickstart/quickstart-microsoft-activedirectory#21]
The max length of the DomainDNSName parameter varies across templates. For Example ad-master-3 and ad-1 templates has a max length of 255 but the ad-master-1 and ad-master-2 template has the max length of 25. I think a restriction of max length 25 is low for DomainDNSName. 

ad-master-1 template

        "DomainDNSName": {
            "AllowedPattern": "[a-zA-Z0-9\\-]+\\..+",
            "Default": "example.com",
            "Description": "Fully qualified domain name (FQDN) of the forest root domain e.g. example.com",
            "MaxLength": "25",

ad-master-3 template

 "DomainDNSName": {
            "AllowedPattern": "[a-zA-Z0-9\\-]+\\..+",
            "Default": "example.com",
            "Description": "Fully qualified domain name (FQDN) of the forest root domain e.g. example.com",
            "MaxLength": "255",

**Comment by SubinGeorge22** [comment]
Submitted a pull request ( https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/22 )

**Comment by virtlima** [comment]
This should be consistent now after the update across templates, please let us know if we missed any.
