### ISSUE TITLE
Error in Install-ADDSForest command in CFT

### ISSUE THREAD

**Issue by Schizamp** [aws-quickstart/quickstart-microsoft-activedirectory#24]
Am testing with the latest Install-ADDSForest script and it's not working. Am seeing this error:

![image](https://user-images.githubusercontent.com/35105617/46031060-dcc83a00-c0c5-11e8-9a23-25b532023232.png)
I logged into the box to see what happened, and the values that are being passed into the Install-ADDSForest script are incorrect.

From the Install-ADDSForest.ps1 transcript:
`Host Application: powershell.exe -Command c:\cfn\scripts\Install-ADDSForest.ps1 -DomainNetBIOSName etrn-addc1 -DomainAdminUser StackAdmin -DomainDNSName awsetrn.etrn.com -SSMParamName CFN-ADPassword-onYissgUM3pU`

But in the script, this is the command being run:
`Install-ADDSForest -DomainName $DomainDNSName -DomainNetbiosName $DomainNetBIOSName -SafeModeAdministratorPassword (ConvertTo-SecureString $DomainAdminPassword -AsPlainText -Force) -DomainMode Default -ForestMode Default  -Confirm:$false -Force`

The value in parameter $DomainNetBIOSName is actually the hostname, as defined by CFT parameter ADServer1NetBIOSName.

Here's the problem right here in the CFT. The CFT needs to be updated for the Quickstart to work.
`"2-install-adds": {
                                "command": {
                                    "Fn::Join": [
                                        "",
                                        [
                                            "powershell.exe -Command c:\\cfn\\scripts\\Install-ADDSForest.ps1 -DomainNetBIOSName ",
                                            {
                                                "Ref": "ADServer1NetBIOSName"
                                            },
                                            " -DomainAdminUser ",
                                            {
                                                "Ref": "DomainAdminUser"
                                            },
                                            " -DomainDNSName ",
                                            {
                                                "Ref": "DomainDNSName"
                                            },
                                            " -SSMParamName ",
                                            {
                                                "Ref": "ADPassword"
                                            }
                                        ]
                                    ]`

Update ADServer1NetBIOSName with DomainNetBIOSName.
_Originally posted by @Schizamp in https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/issue_comments#issuecomment-424430126_

**Comment by Schizamp** [comment]
Yes making this change to the CFT worked. It completed.

**Comment by virtlima** [comment]
Scenario 1 No longer utilizes these scripts, it currently utilizes PowerShell DSC scripts and Modules. If you can try the new setup and provide feedback it would be greatly appreciated. Going to close this issue out now.
