### ISSUE TITLE
The following resource(s) failed to create: [RemoteDesktopGatewaySG, RDGWHostRole

### ISSUE THREAD

**Issue by queglay** [aws-quickstart/quickstart-microsoft-activedirectory#27]
When I attempt to use the quickstart, I get this error while it's trying to to create the Remote Desktop Gateway.
 
`Embedded stack arn:aws:cloudformation:ap-southeast-2:972620357255:stack/Active-Directory-DS-RDGWStack-1FD6NW99W1XIQ/4f63d070-c8fe-11e8-a752-06a653fc8ec8 was not successfully created: The following resource(s) failed to create: [RemoteDesktopGatewaySG, RDGWHostRole, EIP1].`

I ran the quickstart in the Sydney Region.

Thanks if anyone has a solution to this!

**Comment by virtlima** [comment]
How many EIPs are using currently? Looks like the Cloudformation Template was not able to create an EIP, this is sometimes due to the default address limit which is documented [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-limit).

**Comment by queglay** [comment]
Thankyou, I increased the limit and it works now.


Andrew Graham

**Comment by virtlima** [comment]
I am glad you got this resolved, we are looking to make improvement in the RDP Gateway Quick Start where we dont need as many EIPs. Hopefully put it behind a load balancer, so keep an eye for that. Thank you for your feedback.

**Comment by awspd** [comment]
I have a similar issue, except in my case the error is related to ExecutionResourceRole:

The following resource(s) failed to create: [RDGWHostRole, ExecutionResourceRole]
Any ideas what could be causing this?
