### ISSUE TITLE
Time to replace AMI mappings with Parameter Store lookup

### ISSUE THREAD

**Issue by vladibb** [aws-quickstart/quickstart-microsoft-activedirectory#30]
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/6967d02da64c11a937b2da5c344e9c475669eb97/templates/ad-2012r2-2.template#L237-L282

```
Parameters:

  LatestAmazonWindows2012R2AmiId:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: '/aws/service/ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base'

...
    Properties:
      ImageId: !Ref LatestAmazonWindows2012R2AmiId
```

**Comment by vladibb** [comment]
maybe create a new SSM parameter store for QuickStart, after alfred test out all AMIs publish them somwhere like `/aws/service/quickstart-ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base`

**Comment by virtlima** [comment]
We have done this on Scenario 1, I will be sure to update Scenario 2 with the same. We are currently working through all the MSFT Quick Starts to update and utilize this feature. Thank you for your feedback.
