### ISSUE TITLE
Conversion of template to yaml

### ISSUE THREAD

**Issue by queglay** [aws-quickstart/quickstart-microsoft-activedirectory#31]
Without being able to add comments in json, its difficult to use this template as the basis for new company infrastructure.  It would be great if all these examples were converted to yaml.

**Comment by hoshsadiq** [comment]
You can use [cfn-flip](https://github.com/awslabs/aws-cfn-template-flip) to quickly convert it

**Comment by queglay** [comment]
Thanks Hosh, I'll try it out.  currently getting some pip install issues with it but hopefully can work it out.

**Comment by virtlima** [comment]
We recently updated the Quick Start and I tried my best to incorporate this feedback. Scenario 1 is all YAML and I tried to comment as much as possible on the PowerShell Code and the YAML Templates. Thank you for the feedback, and please let us know if there is anything else we can do to improve these quick starts. Thank you.
