### ISSUE TITLE
Failing to create stack - Hangs and fails on second DC

### ISSUE THREAD

**Issue by vennemp** [aws-quickstart/quickstart-microsoft-activedirectory#41]
11:13:22 UTC-0400 | CREATE_FAILED | AWS::EC2::Instance | DomainController2 | Failed to receive 1 resource signal(s) within the specified duration
-- | -- | -- | -- | --

This is the error I received.  I literally ran the stack two days ago and it succeeded.  Now it hangs on the second DC for 20+ minutes and then rolls back.  I am running now again with Rollback disabled..

**Comment by virtlima** [comment]
If you can grab the logs from CloudWatch Logs on that Second Domain Controller to see what is failing. All the Automation runs in AWS Systems Manager, it will also point out which steps failed, and point to the logs. I will run a test now to see if I can replicate. Also, are you running multiple copies of the Quick Start and keeping the naming of the Instances the same? One thing we need to  improve on is using a unique tag as opposed to the name tag. If you have instances with the same Name Tag, that would also cause issues.

**Comment by vennemp** [comment]
Yes I did use the same instance names and IPs...Basically says that the SSM agent isn't on the instance.. which would be a problem.  I am using the default 2019 AMI so I know it's baked in, checked and I realized there were no DHCP options (since the original stack replaced them) and thus the new one was blank.. would make sense if this was the issue since the SSM agent probably using a hostname to connect.. will let you know... Thanks for the quick response.

 ![image](https://user-images.githubusercontent.com/26049891/59122595-29d4ff00-8929-11e9-8ded-0d79a9563ab2.png)

**Comment by virtlima** [comment]
You can use the same Instances names as long as you don't have other instances that currently exist with the same names. The SSM run commands will pick up all Instances in that account\region with the same host names, so that may cause issues. But glad you determine what they issue maybe, keep us up to date.

**Comment by vennemp** [comment]
Thanks! Hope I don't jinx it at this point but it looks like it is working!

![image](https://user-images.githubusercontent.com/26049891/59125379-327d0380-8930-11e9-8b39-46c2aa2ebf72.png)

**Comment by virtlima** [comment]
Nice! Let us know if there is anything we can to do improve this Quick Start. I am going to close this out for now.
