### ISSUE TITLE
Failure to create domain controller for scenario 1

### ISSUE THREAD

**Issue by 0xjjoyy** [aws-quickstart/quickstart-microsoft-activedirectory#42]
Failed to create Domain Controller and receive resource signal for scenario 1 ad-master-1

<img width="832" alt="domain-controller-creation-error" src="https://user-images.githubusercontent.com/48747652/61045488-f6164a80-a3a8-11e9-93c3-99354892456d.png">

**Comment by virtlima** [comment]
Can you go to the CloudWatch Log Input or to AWS Systems Manager and view the Automation Execution that occurred (screenshot included)? There will be more information on why it failed in  the log output if the SSM Automation executed and what steps actually failed. If you dont see an Execution ID, then the nodes can not talk back to the SSM API to launch the Automation. Are you deploying into an existing VPC? 
![image](https://user-images.githubusercontent.com/9896048/61053170-02a39e80-a3bb-11e9-860a-2d1f2d2cb8e5.png)

**Comment by 0xjjoyy** [comment]
Thank you. Unfortunately we deleted the stack and moved onto scenario 3. We were deploying into a new VPC created by the quickstart.

We'll make a note of this if we try scenario 1 again.

**Comment by virtlima** [comment]
No problem, definitely less moving parts in that Scenario. I will be running test again on that just to ensure everything is working correctly.

**Comment by virtlima** [comment]
Scenario1 tested out well through our CI\CD process on 7-11-19, if you disable rollback [](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-prevent-rollback-failure/)Then you can take a look at the CloudWatch Logs to see what may have failed.

**Comment by virtlima** [comment]
Have not heard back on this issue, current test are passing on this Quick Start. Closing this issue.
