### ISSUE TITLE
can't remote into scenario 3 after Create_Complete

### ISSUE THREAD

**Issue by BithsAndH** [aws-quickstart/quickstart-microsoft-activedirectory#43]
Hello, as described above I am not able to remote into the instance after running a default scenario 3 template.  I am not sure if I did something wrong?  Any help would be greatly appreciated.

Thank You!

**Comment by virtlima** [comment]
Are you trying to rdp to the Remote Desktop Gateway? Scenario 3 deploys our [AWS Managed AD](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/directory_microsoft_ad.html) so you will not have access to the Domain Controllers, you would need to install AD Management Tools on another Instances. There you can manage the AD Domain\Forest
