### ISSUE TITLE
how to connect my onpremise DC to Scenario-2 DCs

### ISSUE THREAD

**Issue by nicolasd85** [aws-quickstart/quickstart-microsoft-activedirectory#49]
Hi good morning.
I actually have an OpenVPN AMI on another VPC in the same region where I launched the Scenario-2 master stack. 
I've done the Peering connection between the OpenVPN VPC and the Scenario-2 VPC, I've made a Security group for the traffic coming from the OpenVPN VPC and attached it to the Scenario-2 DC1 and DC2, but still I can't connect to my Scenario-2 DCs. The only way that I managed to connect is associating the private subnets from the Scenario-2 VPC to the route table from that VPC. 
I don't know if this is the right way to do it or if there is a better and correct way to do it.
Can you help me?
@virtlima

**Comment by virtlima** [comment]
@nicolasd85, sorry for responding late, did you get this sorted out?

**Comment by davmayd** [comment]
This has been made optional through automation
