### ISSUE TITLE
Failed to create ADServerRole and ADSsmPassRolePolicy

### ISSUE THREAD

**Issue by elvirk** [aws-quickstart/quickstart-microsoft-activedirectory#50]
Hi,
I'm trying to use this quick start in AWS Gov region and I copied "quickstart-microsoft-activedirectory" to my S3 and modify template to point to my S3.
It failed with following error: Partition "aws" is not valid for resource "arn:aws:iam::accountnumber:role/ADDC-AWSQuickstartADDSRole-number". 
(Service: AmazonIdentityManagement; Status Code: 400, Error Code: malformedPolicyDocument)

**Comment by virtlima** [comment]
Elvirk, please let us know if this is still an issue. When passing the roles and setting the roles they are all using the Pseudo parameter AWS::Partition so it should setup it up correctly for GovCloud. Please let us know if this is still an issue and we will troubleshoot where the issue maybe.

**Comment by mike-newman** [comment]
I ran in to the same issue in GovCloud. in my case "arn:aws:us-gov" needed to be changed to arn:aws-us-gov in resource 'AWSQuickstartADDSRole'.

https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-aws-service-namespaces

**Comment by awspd** [comment]
I'm having the same issue. Made changes indicated by Mike above but to no avail.....

Here's the error I'm seeing now:
Partition "aws" is not valid for resource "arn:aws:s3:::aws-ssm-us-gov-west-1/*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument;

**Comment by davmayd** [comment]
Fixed by https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/114
