### ISSUE TITLE
Ports listed in ad-1.template

### ISSUE THREAD

**Issue by PrivoChapin** [aws-quickstart/quickstart-microsoft-activedirectory#52]
Greetings -

I wanted to double check/review some of the ports listed in ad-1.template and whether they were required for Active Directory or not.

- Remove: TCP/80 [[line 791](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L791)] I don't think HTTP is required?
- Warn About/Remove: TCP/3389 [[line 803](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L803)] [[line 921](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L921)] The RDP port is open to the entire VPC CIDR for both Domain Controllers and Domain Members.  It may be worth mentioning this in the CloudFormation Description?  With Session Manager port forwarding, this may not be necessary, or perhaps can be made as an optional parameter?
- Remove: UDP/445 [[line 838](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L838)] [[line 976](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L976)] [[line 985](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L985)] I _believe_ only TCP/445 is required, but UDP is not. [[source 1](https://support.microsoft.com/en-us/help/179442/how-to-configure-a-firewall-for-domains-and-trusts)] [[source 2](https://support.microsoft.com/en-us/help/832017/service-overview-and-network-port-requirements-for-windows)] I have found a few references for UDP/445 in earlier Server OS versions, so I'm not sure if it was deprecated or just a typo? [[example](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd772723(v=ws.10)?redirectedfrom=MSDN)]
- Remove: TCP/5722 [[line 902](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L902)]
>Port 5722 is only used on a Windows Server 2008 domain controller or on a Windows Server 2008 R2 domain controller.
[[source](https://support.microsoft.com/en-us/help/832017/service-overview-and-network-port-requirements-for-windows)]
- TCP/139 [[line 811](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L811)] [[line 899](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L899)] Line 811 and 899 are duplicate coverage.  Is that port needed for all of the VPC CIDR?
- TCP/445 [[line 807](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L807)] Is SMB needed for all of the VPC CIDR?
- TCP/5985 - [[line 787](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L787)] [[line 917](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L917)] Is WinRM 2.0 required at all?  If so, why for all of the VPC CIDR (domain members too)?
- UDP/5355 - [[line 891](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L891)] is Link-Local Multicast Name Resolution (LLMNR) required?  Generally I see recommendations to disable this.

I also have a question about the need of inbound/ingress rules being defined for 'DomainMembersSG' at all. [[line 915](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/11f0aaf4b083b6c85bfd91d55b49e631433c7c9b/templates/ad-1.template#L915)]  With security groups being stateful, wouldn't the default outbound rule of 0.0.0.0/0 be enough?  I believe this is how the default Amazon WorkSpaces (Windows) is implemented for example (SG: d-#_workspacesMembers).

Lastly, it may be helpful to add a description for each port:
- tcp&udp/53 - DNS
- tcp&udp/88 - Kerberos
- udp/123 - W32Time
- tcp/135 - RPC Endpoint Mapper
- udp/137 - NetBIOS Name Resolution
- udp/138 - NetBIOS Datagram Service
- tcp/139 - NetBIOS Session Service
- tcp&udp/389 - LDAP
- tcp/445 - SMB
- tcp&udp/464 - Kerberos Password V5
- tcp/636 - LDAP SSL
- tcp/3268 - LDAP GC
- tcp/3269 - LDAP GC SSL
- tcp/9389 - Active Directory Web Services (ADWS)

Looking forward to hearing your thoughts.

Cheers,

**Comment by virtlima** [comment]
Thank you for the feedback, we will take a look into the ports, the port list was based on previous version of Windows. We do have plans to move to Session Manager, but we want to keep paradigms people are used to utilizing in the interim. However, this is one of the reasons we open source the Quick Starts to give the community to fork the projects and customize to meet their needs. We also review and accept pull requests as well.
