### ISSUE TITLE
DomainController2 Timeout in Scenario 1

### ISSUE THREAD

**Issue by cdilga** [aws-quickstart/quickstart-microsoft-activedirectory#65]
Attempting to deploy this stack with Scenario 1 using the 

- QuickStart button, 
- Amazon's bucket for ad-master-1.template
- Amazon's bucket for ad-master-1-ssm.template
- Our own VPC with the Amazon ad-1.template
- Custom bucket with ad-master-1.template
- Custom bucket with ad-master-1-ssm.template

Where the Amazon bucket is https://s3.amazonaws.com/aws-quickstart/quickstart-microsoft-activedirectory/templates/

These issues all have the same output as the current issue:
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/issues/54
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/issues/46
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/issues/42

Essentially there is a timeout after DomainController2 is unable to send the [SUCCESS] message. There are several logs observed in the logging group.

Following steps from prior issues we find the following:

runPowerShellScript/stderr
```At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\77cfae4d-ca5d-4a5c-9416-e0f8cbf03d4f\downloads\ConfigDC1-SSM.ps1:96 
char:5
+     Import-DscResource -Module NetworkingDsc
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'NetworkingDsc'.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\77cfae4d-ca5d-4a5c-9416-e0f8cbf03d4f\downloads\ConfigDC1-SSM.ps1:97 
char:5
+     Import-DscResource -Module xActiveDirectory
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'xActiveDirectory'.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\77cfae4d-ca5d-4a5c-9416-e0f8cbf03d4f\downloads\ConfigDC1-SSM.ps1:98 
char:5
+     Import-DscResource -Module ActiveDirectoryCSDsc
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'ActiveDirectoryCSDsc'.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\77cfae4d-ca5d-4a5c-9416-e0f8cbf03d4f\downloads\ConfigDC1-SSM.ps1:99 
char:5
+     Import-DscResource -Module ComputerManagementDsc
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'ComputerManagementDsc'.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\77cfae4d-ca5d-4a5c-9416-e0f8cbf03d4f\downloads\ConfigDC1-SSM.ps1:100 
char:5
+     Import-DscResource -Module xDnsServer
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'xDnsServer'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ModuleNotFoundDuringParse
 
failed to run commands: exit status 255```

```Install-PackageProvider : No match was found for the specified search criteria 
for the provider 'NuGet'. The package provider requires 'PackageManagement' 
and 'Provider' tags. Please check if the specified package has the tags.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\937c5128-4c70-4b92-8889-3056a35a7e87\downloads\install-ad-modules.ps1:8 
char:1
+ Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5 -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvi 
   der:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.Pac 
   kageManagement.Cmdlets.InstallPackageProvider```
```Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell 
is in NonInteractive mode. Read and Prompt functionality is not available."
At C:\Program 
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7392 char:8
+     if($Force -or $psCmdlet.ShouldContinue($shouldContinueQueryMessag ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PSInvalidOperationException
 
Set-PSRepository : NuGet provider is required to interact with NuGet-based 
repositories. Please ensure that '2.8.5.201' or newer version of NuGet 
provider is installed.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0122e4e67148e280a\document\orchestr
ation\937c5128-4c70-4b92-8889-3056a35a7e87\downloads\install-ad-modules.ps1:9 
char:1
+ Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-PSRepository], Invali 
   dOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Set-PSRepository
```

Other logging output exists, but seems to have been successful.
Currently, I have been trying to setup our environment as close to your testing environment as possible but are unable to create a successful deployment.
Is there any steps that can be taken to resolve this issue?

**Comment by neilalex** [comment]
If it means anything, I was able to run scenario 1 earlier today with no issues, using a custom bucket and `ad-master-1.template`. Repo was cloned when the tip was at `077aa1486`. 

I'd ran into the issue you describe when using Amazon's bucket, and it almost _seemed_ like the custom bucket would have the issue as well, as it took the job a solid 45 minutes to work through the DC2 step. Eventually it moved past that though?

**Comment by cdilga** [comment]
Was there anything special you had to do to get the custom bucket working well? 
When I did it, I set the bucket name to `my-completely-unique-bucket-name` and the key to `/` and just uploaded the cloned repo - at 18c6b85a54d740c19d221e63007e2729dda12d9d

Are there implicit assumptions about the key being something other than bucket root `/` or anything similar?

Also, we can verify that using Amazon's buckets from links in the Quickstart are as of this moment broken?

**Comment by neilalex** [comment]
Hm, my repo was in a subfolder in the bucket, though not certain why that would make a difference. Around three months ago I remember having an issue using a bucket in us-east-2, which resolved after I tried us-east-1. Also, when cloning the repo, make sure to use `--recursive` so that the submodules come down?

 &nbsp;
Altogether, the steps I took were --

**In S3:**
Create bucket `my-bucket-name` in us-east-1
Create subfolder `aws`, and then subfolder `aws-quickstart` under that, both with AES-256 encryption

**On a local machine (with git + AWS CLI installed, git set up for use with github), in some temp location:**
```
git clone --recursive git@github.com:aws-quickstart/quickstart-microsoft-activedirectory.git
aws s3 cp --recursive quickstart-microsoft-activedirectory s3://my-bucket-name/aws/aws-quickstart/quickstart-microsoft-activedirectory
```

**CloudFormation, Amazon S3 template URL:**
https://my-bucket-name.s3.amazonaws.com/aws/aws-quickstart/quickstart-microsoft-activedirectory/templates/ad-master-1.template

**CloudFormation, In the template itself:**
_Quick Start S3 Bucket Name:_
my-bucket-name

_Quick Start S3 Key Prefix:_
aws/aws-quickstart/quickstart-microsoft-activedirectory/

 &nbsp;
As for Amazon's buckets via links in the Quickstart being broken, no official idea though I did see that #62 pointed that out too.

**Comment by cdilga** [comment]
Thanks,
What I didn't realise was the necessity to have the `--recursive` flag for the GitRepo, which interestingly fails at the same point 🤔 

I think this issue should remain open until the AWS provided bucket can be updated to work.
However, perhaps updating the Readme or a wiki would help others to setup their own custom buckets and get the quickstart deployed

**Comment by neilalex** [comment]
Ah glad to hear it! I'm just a user though I'd fully support any notes around this in the readme -- definitely spent more time trying to figure that one out myself several months ago than I'd wanted. Sorry it didn't occur to me sooner

**Comment by virtlima** [comment]
@neilalex Thanks for the Suggestion, we try and add a reference to using your own S3 Buckets and the --recursive flag to grab all repos. sorry for the inconvenience. @cdilga where you able to get it running, seems so.

**Comment by davmayd** [comment]
Fixed by https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/114
