### ISSUE TITLE
Domain Controller 2 fails to receive CFN-Signal

### ISSUE THREAD

**Issue by mike-newman** [aws-quickstart/quickstart-microsoft-activedirectory#68]
I have been racking my head on this one for some time. I am running the AD-1.template in GovCloud in an existing VPC. I have all my parameters correct and have even set the Wait Condition to 4 hours but always get the Failed Signal for DC2 to complete configuration. 

Here is the last CloudWatch Log entry. 

VERBOSE: [DC1]: LCM:  [ Start  Resource ]  [[NetAdapterName]RenameNetAdapterPrimary]
VERBOSE: [DC1]: LCM:  [ Start  Test     ]  [[NetAdapterName]RenameNetAdapterPrimary]
VERBOSE: [DC1]:                            [[NetAdapterName]RenameNetAdapterPrimary] Test-TargetResource: Testing the 
network adapter Name 'Primary'.
VERBOSE: [DC1]:                            [[NetAdapterName]RenameNetAdapterPrimary] Find-NetworkAdapter: Finding 
network adapters matching the parameters.
VERBOSE: [DC1]:                            [[NetAdapterName]RenameNetAdapterPrimary] Find-NetworkAdapter: 1 network 
adapters were found matching the parameters.
VERBOSE: [DC1]:                            [[NetAdapterName]RenameNetAdapterPrimary] Test-TargetResource: A network 
adapter was found with the intended new name 'Primary' of the Adapter. No rename required.
VERBOSE: [DC1]: LCM:  [ End    Test     ]  [[NetAdapterName]RenameNetAdapterPrimary]  in 1.5430 seconds.
VERBOSE: [DC1]: LCM:  [ Skip   Set      ]  [[NetAdapterName]RenameNetAdapterPrimary]
VERBOSE: [DC1]: LCM:  [ End    Resource ]  [[NetAdapterName]RenameNetAdapterPrimary]
VERBOSE: [DC1]: LCM:  [ Start  Resource ]  [[User]AdministratorPassword]

16:46:20
VERBOSE: [DC1]: LCM: [ Start Test ] [[User]AdministratorPassword]
VERBOSE: [DC1]: LCM:  [ Start  Test     ]  [[User]AdministratorPassword]

I have since ran the script again, I can view the logs and see that the machine was started and DC1 is configured properly. DC2 instance is launched however none of the PS scripts are run due to the Signal not being sent.  I can also ping each machine from one another.  Any suggestions?

**Comment by mike-newman** [comment]
I have since ran the script again, I can view the logs and see that the machine was started and DC1 is configured properly. DC2 instance is launched however none of the PS scripts are run due to the Signal not being sent.  I can also ping each machine from one another.  Any suggestions?

**Comment by cdilga** [comment]
As far as I can tell @mike-newman the public buckets referenced by the quickstart are simply broken.

Instructions on how to successfully deploy are in this open issue: https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/issues/65

**Comment by mike-newman** [comment]
@cdilga --

I should have been more clear, I have created internal buckets and had been following the solution to your post by pushing the repo to S3.  Also, I am not running the ad-master-1.template. I have no need for the RDG's but I suppose I could strip out items not needed from the master template.  I am running "ad-master-1.template" which according to the documentation is to deploy 2 DC's in to an existing VPC. 

Additionally, my issue experienced is not the same as your original post. All the modules are sucessfully installed (as far as I can tell) and DC1 is successfully created but fails to send the CFN-Signal to DC2 for the same iteration of powershell script installations.  I have been racking my head on this for a couple weeks and could appreciate any assistance. 

MN

**Comment by virtlima** [comment]
Can you verify if the IAM Policy that is created [here](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/077aa14866e7d103de572fc2ea52f2be508364d0/templates/ad-1-yaml.template#L698-L711) looks correct in your account. Wondering if the AWS Systems Manager Automation Steps has the ability to signal the resource. 

In AWS Systems Manager are all steps in the automation completing successfully? Have any of them failed?

**Comment by mike-newman** [comment]
@virtlima  Thank you for the reply.

Here is the Policy I have, I had to change the document as this is for GovCloud and the ARNS are different. 

```- PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws-us-gov:s3:::aws-ssm-${AWS::Region}/*'
                  - !Sub 'arn:aws-us-gov:s3:::aws-windows-downloads-${AWS::Region}/*'
                  - !Sub 'arn:aws-us-gov:s3:::amazon-ssm-${AWS::Region}/*'
                  - !Sub 'arn:aws-us-gov:s3:::amazon-ssm-packages-${AWS::Region}/*'
                  - !Sub 'arn:aws-us-gov:s3:::${AWS::Region}-birdwatcher-prod/*'
                  - !Sub 'arn:aws-us-gov:s3:::patch-baseline-snapshot-${AWS::Region}/*'
                Effect: Allow
          PolicyName: ssm-custom-s3-policy
```

Systems Manager seems to complete as far as I can tell. I'll re-run the stack and get more verbose output.

**Comment by virtlima** [comment]
@mike-newman sorry for not responding sooner, have you been able to figure out the issue? I wonder if there is something off with the IAM policy that is not allowing the signaling in gov-cloud.

**Comment by davmayd** [comment]
Fixed by https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/114
