### ISSUE TITLE
ConfigDC1.ps1 has missing Parameters

### ISSUE THREAD

**Issue by jmwyson** [aws-quickstart/quickstart-microsoft-activedirectory#69]
I'm getting below error when trying to run scenario 1.

```
C:\ProgramData\Amazon\SSM\InstanceData\i-0955fb4db3df03d62\document\orchestrati
on\7a564895-984e-4f81-bfa7-539e6974ac6f\downloads\ConfigDC1.ps1 : A parameter 
cannot be found that matches parameter name 'PrivateSubnet1CIDR
```

Looking at the code, it seems ConfigDC1.ps1 doesn't define this parameter in its list of parameters. Yet, `ad-1-yaml.template` calls ConfigDC1.ps1 with PrivateSubnet1CIDR parameter.

```
commandLine: "./ConfigDC1.ps1 -ADServer1NetBIOSName {{ADServer1NetBIOSName}} -DomainNetBIOSName {{DomainNetBIOSName}} -DomainDNSName {{DomainDNSName}} -ADAdminSecParam {{ADAdminSecParamName}} -ADAltUserSecParam {{ADAltUserSecParamName}} -RestoreModeSecParam {{RestoreModeSecParamName}} -SiteName {{global:REGION}} -PrivateSubnet1CIDR {{PrivateSubnet1CIDR}} -PublicSubnet1CIDR {{PublicSubnet1CIDR}} -PrivateSubnet2CIDR {{PrivateSubnet2CIDR}} -PublicSubnet2CIDR {{PublicSubnet2CIDR}}"
```

**Comment by virtlima** [comment]
jmwyson, 
The ad-1-yaml.template in  the directory was left there as a reference, probably should note that. It is not what is being used off the Quick Start Launch page. Looking at the template it doesn't reflect an update we made. We will try to fix that today, at one point we were creating sites based on subnets, we know create sites by region. That is why the ConfigDC1.ps1 does not take the PrivateSubnet1CIDR parameter. 

The ad-1.template is up to date and if you use that one it should not cause an error. Please let us know. We will update or drop the ad-1-yaml.template. Thanks for bringing this to our attention, sorry for the inconvenience.
