### ISSUE TITLE
Hangs on DomainController1WaitCondition

### ISSUE THREAD

**Issue by smulikHakipod** [aws-quickstart/quickstart-microsoft-activedirectory#7]
Hey,
I try to use 
Template_1_AD_2012R2.template
But it hangs on 
DomainController1WaitCondition
Those are the parameters
![image](https://user-images.githubusercontent.com/4186903/36500219-5ebd35ac-174c-11e8-9be5-ac4ae2fac70b.png)
I put quite strong password, at least 8 chars with both numbers lower upper and digits.
After a long time I get:
```
Embedded stack <...> was not successfully created: The following resource(s) failed to create: [DomainController1WaitCondition].
```
Any ideas?
Thanks

**Comment by kamarja** [comment]
Hey,
We will be deprecating Template_1_AD_2012R2.template. Please use ad-1.template instead.

**Comment by smulikHakipod** [comment]
I am not using it directly, it is part of aws-quickstart/quickstart-microsoft-sharepoint. Will changing the template manually for now in the sharepoint will work?

**Comment by kamarja** [comment]
I am currently testing the updated Sharepoint Quick Start. I will ping you here when it's available.

**Comment by urashidmalik** [comment]
Update to scripts/ConvertTo-EnterpriseAdmin.ps1 has broken all the Cloudformation deployment. that were using 2012R2

**Comment by urashidmalik** [comment]
Is their an option to access old Script at different s3 endpoint?

https://s3.amazonaws.com/quickstart-reference/microsoft/activedirectory/latest/scripts/ConvertTo-EnterpriseAdmin.ps1

Instead of latest we can have 2012?

**Comment by kamarja** [comment]
Hey,
Thanks for reporting this, I am modifying the script so it's compatible with 2012.

**Comment by urashidmalik** [comment]
Thank you @kamarja

**Comment by kamarja** [comment]
Hi,
Please try now and let me know how it goes.

**Comment by jason-archidera** [comment]
My template is also hanging on DomainController1WaitCondition.

I'm using https://s3.amazonaws.com/quickstart-reference/microsoft/activedirectory/latest/templates/ad-master-1.template, so it's the latest.  

With that said, our requirement is to use Server 2012r2, does that work still?

**Comment by virtlima** [comment]
We have updated Scenario 1 in this quick start, from a quick start perspective we will be supporting 2016 and newer. Any older OSes, you will have to test and ensure it utilize WMF 5.1 or above. The update utilize PowerShell DSC Modules to configure AD. I am going to close this out, please try the update and provide feedback.
