### ISSUE TITLE
Mismatch of RDGWInstanceType AllowedValues between rdgw-domain.template and ad-master templates

### ISSUE THREAD

**Issue by ErikOAWS** [aws-quickstart/quickstart-microsoft-activedirectory#76]
There's a discrepancy in allowed instance types for the RDGW Instance Type which allows the user to specify an instance type in the master which is not valid the the nested template.

## ad-master-3.template
RDGWInstanceType:
    Description: Amazon EC2 instance type for the Remote Desktop Gateway instances
    Type: String
    Default: t3.large
    AllowedValues:
      - **_t2.small_**
      - **_t2.medium_**
      - t2.large
      - t3.small
      - t3.medium
      - t3.large
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - **_m5.4xlarge_**

## rdgw-domain.template 
RDGWInstanceType:
    Description: Amazon EC2 instance type for the Remote Desktop Gateway instances
    Type: String
    Default: t3.2xlarge
    AllowedValues:
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - t3a.micro
      - t3a.small
      - t3a.medium
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge

Specifying *t2.small*, *t2.medium* or *m5.4xlarge* in the master stack will cause the RDGWStack stack creation to fail.

**Comment by girvenj** [comment]
I am working on the rdgw-domain.template due to another issue. I will update that to include the instance types

**Comment by girvenj** [comment]
Here is the pull that will fix this: https://github.com/aws-quickstart/quickstart-microsoft-rdgateway/pull/34
