### ISSUE TITLE
CloudWatch logs display plaintext credentials

### ISSUE THREAD

**Issue by davmayd** [aws-quickstart/quickstart-microsoft-activedirectory#92]
When Secrets Manager secrets are converted by SSM, the plaintext passwords are recorded in CloudWatch logs

**Comment by davmayd** [comment]
![image](https://user-images.githubusercontent.com/51335587/110216014-5efde080-7e72-11eb-8dec-58ba89c0735d.png)

**Comment by girvenj** [comment]
My last commit should fix that: Looks like it is not in the main branch
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/commit/87ac4707027d41b472a695cc370a739cda24cd7e
