### ISSUE TITLE
Errant links at Quick Start site

### ISSUE THREAD

**Issue by john-aws** [aws-quickstart/quickstart-microsoft-activedirectory#93]
Hi, several links in the [Launch the Quick Start](https://aws-quickstart.github.io/quickstart-microsoft-activedirectory/#_launch_the_quick_start) table at [Active Directory on the AWS Cloud
Quick Start Reference Deployment](https://aws-quickstart.github.io/quickstart-microsoft-activedirectory/) point to http://qs_launch_permalink/. For example: `Deploy self-managed Active Directory into a new VPC on AWS`.

These links do not function.

**Comment by john-aws** [comment]
Also, a second minor issue: the `Deploy self-managed Active Directory into a new VPC on AWS` template link is incorrect:

> https//github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/main/templates/ad-master-1.template

Note the https protocol is missing a colon.

**Comment by davmayd** [comment]
These have been updated
