### ISSUE TITLE
Not an Enterprise CA

### ISSUE THREAD

**Issue by john-aws** [aws-quickstart/quickstart-microsoft-activedirectory#98]
Hi, the [mgmt-1.template](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/main/templates/mgmt-1.template) description claims to deploy an Enterprise CA. When I RDP into this instance, its list of server roles does not include Active Directory Certificate Services and certsrv.msc is not found.

Is the description wrong, or could CA feature installation have failed?

**Comment by girvenj** [comment]
Wording was fixed on this
